### ISSUE TITLE
Adding a constraint to resize

### ISSUE THREAD

**Issue by davidrichied** [getdave/wp-intervention#6]
Hi,
Thanks for the plugin! It works great.
Is it possible to include a callback function to constrain the aspect ratio?
I am trying to resize the image to a height of 400px while maintaining the aspect ratio for the width.
Here's how it's done with plain Intervention: [http://image.intervention.io/api/resize](http://image.intervention.io/api/resize)
Thanks.

**Comment by davidrichied** [comment]
I found out how to do it.
Here's what I did for anyone else looking for the solution. I just had to add a function as the third item in the $intervention_args array.

`$imageUrl = $image['url'];

$imagePath = wp_make_link_relative($imageUrl);

$imageAbsPath = ABSPATH . substr($imagePath, 1);

// An array of args to be *invoked* on Intervention
$intervention_args = array( 
	'resize' => array(
		null,
		'400',
		function($constraint) {
    	$constraint->aspectRatio();
    }
	),

);
$thumbnail = wp_intervention( $imageAbsPath, $intervention_args ); `

**Comment by getdave** [comment]
Hi @davidrichied. Glad you found a solution. Can I ask was it clear enough in the README docs as to how to achieve your solution?

**Comment by davidrichied** [comment]
Hi @getdave , 
I think I got lucky by playing around with adding the function in different places.
